name = "hakuro-hono"
main = "src/index.ts"
compatibility_date = "2024-10-19"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "hakuro-hono"
database_id = "6b0e9554-cb69-4898-bc1d-8907ccc78172"



